import type { WorldDistrict, WorldLocation, WorldRegionSlug } from './world-types'

export const WORLD_DISTRICTS: WorldDistrict[] = [
  { id: 'doha', slug: 'doha', name: 'Doha', description: 'The city heart: a bright starting point for everyday stories.', regionSlug: 'doha', mapX: 33, mapY: 38, sortOrder: 10 },
  { id: 'souq-district', slug: 'souq-district', name: 'Souq district', description: 'Lantern-lit lanes, karak stops and small discoveries after sunset.', regionSlug: 'doha', mapX: 27, mapY: 30, sortOrder: 20 },
  { id: 'corniche', slug: 'corniche', name: 'Corniche', description: 'A waterfront promenade made for walks, photos and sea air.', regionSlug: 'doha', mapX: 42, mapY: 34, sortOrder: 30 },
  { id: 'msheireb', slug: 'msheireb', name: 'Msheireb', description: 'Courtyards, cafés and creative work in a walkable quarter.', regionSlug: 'doha', mapX: 36, mapY: 44, sortOrder: 40 },
  { id: 'west-bay', slug: 'west-bay', name: 'West Bay', description: 'Skyline energy, plazas and the pulse of modern work.', regionSlug: 'doha', mapX: 50, mapY: 27, sortOrder: 50 },
  { id: 'katara', slug: 'katara', name: 'Katara', description: 'Art, performance and community by the cultural shore.', regionSlug: 'doha', mapX: 59, mapY: 35, sortOrder: 60 },
  { id: 'the-pearl', slug: 'the-pearl', name: 'The Pearl', description: 'Marina days, waterfront residences and relaxed evenings.', regionSlug: 'the-pearl', mapX: 69, mapY: 25, sortOrder: 70 },
  { id: 'lusail', slug: 'lusail', name: 'Lusail', description: 'Boulevards, sports nights and a future-facing skyline.', regionSlug: 'lusail', mapX: 79, mapY: 35, sortOrder: 80 },
  { id: 'desert', slug: 'desert', name: 'Desert', description: 'Open horizons, quiet routes and stars beyond the city.', regionSlug: 'outside-doha', mapX: 52, mapY: 73, sortOrder: 90 },
  { id: 'beach', slug: 'beach', name: 'Beach', description: 'Sand, water and a slower day by the fictional shoreline.', regionSlug: 'outside-doha', mapX: 71, mapY: 73, sortOrder: 100 },
]

const point = (id: string, name: string, type: WorldLocation['interactionPoints'][number]['type'], x: number, y: number) => ({ id, name, type, x, y })

export const WORLD_LOCATIONS: WorldLocation[] = [
  { id: 'doha-gateway', slug: 'doha-gateway', name: 'Doha Gateway', description: 'A welcoming city square where new residents find their bearings.', districtId: 'doha', district: 'Doha', regionSlug: 'doha', coordinates: { x: 48, y: 52 }, type: 'city-square', openingStatus: 'open', activities: ['city stroll', 'meet neighbours', 'find a route'], interactionPoints: [point('doha-gateway-info', 'Story desk', 'social', 44, 48), point('doha-gateway-metro', 'Metro entrance', 'transport', 61, 57)] },
  { id: 'doha-garden-plaza', slug: 'doha-garden-plaza', name: 'Garden plaza', description: 'A shaded urban garden for a quiet pause between plans.', districtId: 'doha', district: 'Doha', regionSlug: 'doha', coordinates: { x: 72, y: 34 }, type: 'plaza', openingStatus: 'open', activities: ['photography', 'social pause', 'walking'], interactionPoints: [point('doha-garden-fountain', 'Fountain', 'scenery', 70, 32), point('doha-garden-bench', 'Garden bench', 'social', 81, 40)] },
  { id: 'souq-lantern-lane', slug: 'souq-lantern-lane', name: 'Lantern lane', description: 'A fictional market lane filled with colour, craft and small conversations.', districtId: 'souq-district', district: 'Souq district', regionSlug: 'doha', coordinates: { x: 28, y: 43 }, type: 'market', openingStatus: 'open', activities: ['souq exploration', 'shopping', 'photography'], interactionPoints: [point('souq-lantern-stall', 'Lantern stall', 'shop', 34, 43), point('souq-story-corner', 'Story corner', 'social', 21, 50)] },
  { id: 'souq-karak-courtyard', slug: 'souq-karak-courtyard', name: 'Karak courtyard', description: 'A warm courtyard for a fictional karak stop and evening meet-ups.', districtId: 'souq-district', district: 'Souq district', regionSlug: 'doha', coordinates: { x: 69, y: 61 }, type: 'cafe', openingStatus: 'open', activities: ['karak stop', 'social', 'cultural chat'], interactionPoints: [point('souq-karak-counter', 'Karak counter', 'activity', 70, 56), point('souq-courtyard-seats', 'Courtyard seats', 'social', 55, 72)] },
  { id: 'corniche-waterfront', slug: 'corniche-waterfront', name: 'Corniche waterfront', description: 'A long, breezy route with skyline views and room to wander.', districtId: 'corniche', district: 'Corniche', regionSlug: 'doha', coordinates: { x: 32, y: 38 }, type: 'waterfront', openingStatus: 'open', activities: ['walking', 'photography', 'dhow experience'], interactionPoints: [point('corniche-viewpoint', 'Skyline viewpoint', 'scenery', 30, 35), point('corniche-dhow-pier', 'Dhow pier', 'activity', 47, 56)] },
  { id: 'corniche-dhow-pier', slug: 'corniche-dhow-pier', name: 'Dhow pier', description: 'A fictional pier for a slow dhow-inspired cruise and sea views.', districtId: 'corniche', district: 'Corniche', regionSlug: 'doha', coordinates: { x: 70, y: 63 }, type: 'pier', openingStatus: 'open', activities: ['dhow cruise', 'fishing', 'photography'], interactionPoints: [point('corniche-boat-board', 'Boarding point', 'activity', 72, 58), point('corniche-fishing-edge', 'Fishing edge', 'activity', 83, 68)] },
  { id: 'msheireb-courtyard', slug: 'msheireb-courtyard', name: 'Msheireb courtyard', description: 'A polished pedestrian square with cafés and cool shade.', districtId: 'msheireb', district: 'Msheireb', regionSlug: 'doha', coordinates: { x: 43, y: 43 }, type: 'quarter', openingStatus: 'open', activities: ['café visit', 'social', 'shopping'], interactionPoints: [point('msheireb-cafe', 'Courtyard café', 'shop', 38, 35), point('msheireb-water', 'Cool water wall', 'scenery', 61, 49)] },
  { id: 'msheireb-art-house', slug: 'msheireb-art-house', name: 'Art house', description: 'A fictional creative house for exhibitions, workshops and quiet work.', districtId: 'msheireb', district: 'Msheireb', regionSlug: 'doha', coordinates: { x: 70, y: 73 }, type: 'cultural', openingStatus: 'open', activities: ['museum visit', 'photography', 'creative workshop'], interactionPoints: [point('msheireb-gallery', 'Gallery entrance', 'activity', 64, 69), point('msheireb-studio', 'Open studio', 'social', 77, 82)] },
  { id: 'west-bay-skyline', slug: 'west-bay-skyline', name: 'Skyline plaza', description: 'High-rise silhouettes and a wide plaza for ambitious new chapters.', districtId: 'west-bay', district: 'West Bay', regionSlug: 'doha', coordinates: { x: 42, y: 40 }, type: 'business', openingStatus: 'open', activities: ['find work', 'photography', 'social'], interactionPoints: [point('west-bay-transit', 'Transit stop', 'transport', 32, 51), point('west-bay-view', 'Skyline deck', 'scenery', 63, 32)] },
  { id: 'west-bay-work-hub', slug: 'west-bay-work-hub', name: 'Work hub', description: 'A fictional co-working floor for focused tasks and chance meetings.', districtId: 'west-bay', district: 'West Bay', regionSlug: 'doha', coordinates: { x: 70, y: 68 }, type: 'workplace', openingStatus: 'open', activities: ['work session', 'meet people', 'learn'], interactionPoints: [point('west-bay-reception', 'Reception', 'social', 63, 61), point('west-bay-lift', 'Lift lobby', 'transport', 82, 72)] },
  { id: 'katara-cultural-shore', slug: 'katara-cultural-shore', name: 'Cultural shore', description: 'A fictional cultural promenade where art meets the sea.', districtId: 'katara', district: 'Katara', regionSlug: 'doha', coordinates: { x: 35, y: 48 }, type: 'cultural', openingStatus: 'open', activities: ['cultural festival', 'photography', 'beach walk'], interactionPoints: [point('katara-stage', 'Open stage', 'activity', 40, 40), point('katara-shore', 'Shoreline', 'scenery', 26, 66)] },
  { id: 'katara-amphitheatre', slug: 'katara-amphitheatre', name: 'Amphitheatre steps', description: 'A fictional open-air stage for events and community gatherings.', districtId: 'katara', district: 'Katara', regionSlug: 'doha', coordinates: { x: 69, y: 67 }, type: 'event-space', openingStatus: 'open', activities: ['event', 'music', 'social'], interactionPoints: [point('katara-stage-door', 'Stage door', 'activity', 73, 58), point('katara-meetup', 'Meet-up steps', 'social', 61, 78)] },
  { id: 'pearl-marina', slug: 'pearl-marina', name: 'Pearl marina', description: 'A calm marina promenade for boats, breezes and bright evenings.', districtId: 'the-pearl', district: 'The Pearl', regionSlug: 'the-pearl', coordinates: { x: 35, y: 43 }, type: 'marina', openingStatus: 'open', activities: ['dhow experience', 'dining', 'photography'], interactionPoints: [point('pearl-marina-pier', 'Marina pier', 'activity', 39, 54), point('pearl-marina-cafe', 'Waterfront café', 'shop', 55, 31)] },
  { id: 'pearl-promenade', slug: 'pearl-promenade', name: 'Pearl promenade', description: 'A fictional waterfront loop with residences, shops and people-watching.', districtId: 'the-pearl', district: 'The Pearl', regionSlug: 'the-pearl', coordinates: { x: 68, y: 64 }, type: 'residential', openingStatus: 'open', activities: ['shopping', 'walking', 'meet neighbours'], interactionPoints: [point('pearl-promenade-boutique', 'Boutique row', 'shop', 73, 56), point('pearl-promenade-seats', 'Marina seats', 'social', 60, 76)] },
  { id: 'lusail-boulevard', slug: 'lusail-boulevard', name: 'Lusail boulevard', description: 'A wide fictional boulevard built for lights, events and late walks.', districtId: 'lusail', district: 'Lusail', regionSlug: 'lusail', coordinates: { x: 31, y: 45 }, type: 'boulevard', openingStatus: 'open', activities: ['events', 'shopping', 'night walk'], interactionPoints: [point('lusail-light-arch', 'Light arch', 'scenery', 37, 35), point('lusail-transit', 'Transit platform', 'transport', 25, 62)] },
  { id: 'lusail-stadium-district', slug: 'lusail-stadium-district', name: 'Stadium district', description: 'A fictional sports district for fans, friends and community matches.', districtId: 'lusail', district: 'Lusail', regionSlug: 'lusail', coordinates: { x: 68, y: 69 }, type: 'sports', openingStatus: 'open', activities: ['football', 'event', 'social'], interactionPoints: [point('lusail-match-gate', 'Match gate', 'activity', 71, 58), point('lusail-fan-zone', 'Fan zone', 'social', 57, 77)] },
  { id: 'desert-camp', slug: 'desert-camp', name: 'Desert camp', description: 'A fictional camp beyond the city for calm skies and shared stories.', districtId: 'desert', district: 'Desert', regionSlug: 'outside-doha', coordinates: { x: 43, y: 44 }, type: 'nature', openingStatus: 'seasonal', activities: ['desert trip', 'camel experience', 'stargazing'], interactionPoints: [point('desert-campfire', 'Campfire', 'social', 46, 50), point('desert-camel-track', 'Camel track', 'activity', 65, 37)] },
  { id: 'desert-stars', slug: 'desert-stars', name: 'Star route', description: 'A quiet fictional route for photography and open horizons.', districtId: 'desert', district: 'Desert', regionSlug: 'outside-doha', coordinates: { x: 70, y: 70 }, type: 'nature', openingStatus: 'seasonal', activities: ['photography', 'stargazing', 'fishing'], interactionPoints: [point('desert-lookout', 'Lookout', 'scenery', 73, 63), point('desert-photo-mark', 'Photo marker', 'activity', 54, 78)] },
  { id: 'beach-tide-cove', slug: 'beach-tide-cove', name: 'Tide cove', description: 'A fictional beach cove for water, sand and a slower afternoon.', districtId: 'beach', district: 'Beach', regionSlug: 'outside-doha', coordinates: { x: 38, y: 46 }, type: 'beach', openingStatus: 'open', activities: ['beach visit', 'fishing', 'photography'], interactionPoints: [point('beach-cove-water', 'Waterline', 'activity', 42, 63), point('beach-cove-shade', 'Shade tent', 'social', 26, 37)] },
  { id: 'beach-sailing-point', slug: 'beach-sailing-point', name: 'Sailing point', description: 'A fictional shoreline launch for water activities and sunset meet-ups.', districtId: 'beach', district: 'Beach', regionSlug: 'outside-doha', coordinates: { x: 69, y: 67 }, type: 'beach', openingStatus: 'open', activities: ['dhow experience', 'fishing', 'social'], interactionPoints: [point('beach-sailing-launch', 'Launch point', 'activity', 71, 59), point('beach-sailing-sunset', 'Sunset marker', 'scenery', 82, 79)] },
]

export function getDistrictById(id: string) {
  return WORLD_DISTRICTS.find((district) => district.id === id || district.slug === id) ?? null
}

export function getLocationById(id: string) {
  return WORLD_LOCATIONS.find((location) => location.id === id || location.slug === id) ?? null
}

export function getSpawnLocationForRegion(region: WorldRegionSlug | null) {
  const preferred = region === 'the-pearl' ? 'pearl-marina' : region === 'lusail' ? 'lusail-boulevard' : region === 'outside-doha' ? 'beach-tide-cove' : 'doha-gateway'
  return getLocationById(preferred)!
}
